### ISSUE TITLE
The python2.7 was so older that i can not install the module that your workflow need

### ISSUE THREAD

**Issue by honghh2018** [AllonKleinLab/SPRING_dev#28]
Hi, developer
    I want to return the spring_dev, but i get the module miss error, like below:

     
![9835bca8486868ce080bfc6c3010d9b](https://user-images.githubusercontent.com/41668708/148045495-1b39ee35-c6f7-4971-ac75-3108e180900a.png)
![3924301455e34a35dacb1976014c3c9](https://user-images.githubusercontent.com/41668708/148045510-8eaea197-9e88-45c7-913a-e9541d952a67.png)
![64b0c942406e2c11c78c3f137c71a43](https://user-images.githubusercontent.com/41668708/148045524-f5c435cf-9d5c-4724-9f42-b33e3c9f7846.png)

this module can not be install by pip.i already had solve the  the preprocessing_python and the helper_functions module.
but the tables can not be solved by myself. it was complicated than i though.
Hope you help to fix this issue.
Best
Hanhuihong

**Comment by honghh2018** [comment]
Hi @calebweinreb @AllonMKlein everybody,
    Had anyone hear this?

Best
Hanhuihong

**Comment by honghh2018** [comment]
Hi @AllonMKlein,
     how can i do for this issue?

**Comment by calebweinreb** [comment]
There are no immediate plans for an upgrade to python3.

Can you try installing the tables module via conda? ```conda install
pytables```. This worked for me using python 2.7

**Comment by honghh2018** [comment]
Hi @calebweinreb ,
     Excellent, it work on my virtual environmnt. you are bloody genius, and tremendously give me a mega help for this urgent project.
     Thanks, God bless you
Best

**Comment by honghh2018** [comment]
Hi @calebweinreb ,
There is another issue showing up.
the code lying below:

#Save merged samples
merge_setup = {'/Dataset_v1':sample_list}
for s, smerge in merge_setup.items():
    print smerge
    t0 = time.time()
    print t0
    print '________________', s
    
    cell_ix = np.in1d(samp_id_flat, smerge)
    
    run_all_spring_1_6(E[cell_ix,:],
                     list(merged_list), s, main_spring_dir, normalize=False, tot_counts_final = total_counts[cell_ix],
                     min_counts = 3, min_cells = 3, min_vscore_pctl = 90, 
                     show_vscore_plot = True, num_pc = 50, pca_method = '', k_neigh=4, use_approxnn = False,
                     output_spring = True, num_force_iter = 2000,
                     cell_groupings = {'Sample': list(samp_id_flat[cell_ix])})
    
    print time.time() - t0
    
    np.save(main_spring_dir + s + '/cell_filter.npy', np.nonzero(cell_ix)[0])
    np.savetxt(main_spring_dir + s + '/cell_filter.txt', np.nonzero(cell_ix)[0], fmt='%i')
    
    print time.time() - t0
# the error showing below:
['CTRL2', 'FI_3M', 'SRR8872326', 'SRR8872330', 'WT5M1', 'WT6W', 'F20_3M', 'PRT17', 'SRR8872327', 'SRR8872331', 'WT15M', 'WT5M2', 'WT9M']
1643102870.03
________________ /Dataset_v1
Filtering genes
Using 1835 genes
Running PCA
Building kNN graph
kNN built in 192.32610 sec
Saving SPRING files to /share/nas1/Data/Users/honghh/temp/spring-dev/test_data/Dataset_v1
{'Total Counts': array([1149, 2069, 2547, ..., 1361, 1552,  727])}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-40d0cc14b939> in <module>()
     14                      show_vscore_plot = True, num_pc = 50, pca_method = '', k_neigh=4, use_approxnn = False,
     15                      output_spring = True, num_force_iter = 2000,
---> 16                      cell_groupings = {'Sample': list(samp_id_flat[cell_ix])})
     17 
     18     print time.time() - t0

<ipython-input-33-f4078daf8e2f> in run_all_spring_1_6(E, gene_list, sample_name, save_dir, base_ix, normalize, exclude_dominant_frac, min_counts, min_cells, min_vscore_pctl, show_vscore_plot, exclude_gene_names, num_pc, pca_method, pca_norm, k_neigh, cell_groupings, num_force_iter, output_spring, precomputed_pca, gene_filter, custom_colors, exclude_corr_genes_list, exclude_corr_genes_minCorr, dist_metric, use_approxnn, run_doub_detector, dd_k, dd_frac, dd_approx, tot_counts_final)
    113             save_spring_dir_sparse_hdf5(E, [], 0, gene_list, save_path,
    114                             custom_colors = custom_colors, edges=list(links),
--> 115                             cell_groupings = cell_groupings)
    116         else:
    117             save_spring_dir_sparse_hdf5(E, [], 0, gene_list, save_path,

TypeError: save_spring_dir_sparse_hdf5() got multiple values for keyword argument 'custom_colors'

how can i fix this issue?
Any advices would be appreciated.
Best,
Hanhuihong

**Comment by calebweinreb** [comment]
Can you send the data and notebook that led to the error? (calebsw@gmail.com)

**Comment by honghh2018** [comment]
Hi @calebweinreb ,
     The ipynb file and the data had been sent to you from the 939869915@qq.com email.
Hope the reply.
Best
Hanhuihong

**Comment by honghh2018** [comment]
Hi @calebweinreb ,
    Had any advices for this circumstance?

Best,
Hanhuihong

**Comment by honghh2018** [comment]
Hi @calebweinreb
Is data had received ? 
Had anyone feedback this issue? if having any question please let me know. I am be glad to help.

**Comment by honghh2018** [comment]
Had anyone hear this circumstance？

**Comment by calebweinreb** [comment]
Hi,

I'm very sorry for the late reply. In regard to the specific error, it
seems to arise because save_spring_dir_sparse_hdf5 is defined as taking 4
position arguments and 2 keyword arguments, whereas in run_all_spring_1_6
it is being called with 5 positional arguments.

Zooming out, it seems like this notebook is using functions that were
copied from within cgi_bin? The code in cgi_bin is only intended for our
web backend. To generate SPRING plots locally using a notebook, we
recommend one of the recipes in the data_prep directory (e.g.
https://github.com/AllonKleinLab/SPRING_dev/blob/master/data_prep/spring_example_pbmc4k.ipynb).
All the helper functions for these notebooks should be imported from
spring_helper.py

**Comment by honghh2018** [comment]
Very grateful for the reply.
I have carefully checked the spring_example_pbmc4k.ipynb but found the weird question,
It can not found the spring_helper  directory when Running the header of the notebook with  from spring_helper import * .
It is  strange that download the spring_dev software, because of the module of spring_helper  can not be imported properly with conda environment.

>>> %pylab inline
  File "<stdin>", line 1
    %pylab inline
    ^
SyntaxError: invalid syntax
>>> from spring_helper import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named spring_helper
>>> from doublet_detector import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named doublet_detector
>>> from collections import defaultdict

# the spring setup following you github project workflow

Best,
Hanhuihong

**Comment by calebweinreb** [comment]
Since SPRING is not 'installed' in the environment, all the imports have to
be from files that are in the current directory (or at least you need to
add the path to them using sys.path.append). Is the spring_helpers.py file
in the same directory that you are running the notebook from?

**Comment by honghh2018** [comment]
Hi @calebweinreb , 
    Thanks the advices, The issue have be solved by your alert. I manually create a prep_data dir and bring the helper_funciton.py into it and then import it. 
    This way can work well.
Hope the Best for you
My friends
